# fly.toml app configuration file generated for conservami on 2024-01-29T10:51:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conservami'
primary_region = 'cdg'

[build]
  image = "localhost/conservami-backend:0.1.0-SNAPSHOT"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
