addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.9.16")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"             % "0.5.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.12.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.12.0")
addSbtPlugin("io.github.cquiroz"  % "sbt-tzdb"                 % "4.2.0")
